### ISSUE TITLE
vim-lsp-ultisnips works well with cpp, rust, but not go(gopls)

### ISSUE THREAD

**Issue by hujianxin** [thomasfaingnaert/vim-lsp-ultisnips#11]
vim-lsp-ultisnips works well with cpp, rust, but not works with go(gopls)

**Comment by thomasfaingnaert** [comment]
Could you provide a log file?

**Comment by hujianxin** [comment]
Thanks for your quick reply.

Do you mean lsp log file? this is a complete log from opening a go file to complete snippets failed.
https://gist.github.com/hujianxin/dfed12d2f7905ea77ab363bf1ed1f70b

**Comment by hujianxin** [comment]
http://g.recordit.co/iD9SWiLLB2.gif

Here is a gif I just recored to repreduce this issue.

As is showing in the gif, I failed to complete snippet in golang(gopls), bug sucessed in cpp(clangd)

**Comment by thomasfaingnaert** [comment]
What's not working exactly? Judging from the GIF, it seems to work correctly.
If you mean that when you select `Printf`, there is no "placeholder text" (like `Printf(string)`) but just `Printf()`, then that's because the language server you're using doesn't supply a placeholder text, as can be seen from the log (`newText`):
```json
{
    "label": "Printf",
    "insertTextFormat": 2,
    "command": {
        "title": "",
        "command": "editor.action.triggerParameterHints"
    },
    "sortText": "00001",
    "kind": 3,
    "filterText": "Print",
    "documentation": "Printf formats according to a format specifier and writes to standard output.\nIt returns the number of bytes written and any write error encountered.\n",
    "textEdit": {
        "range": {
            "end": {
                "character": 10,
                "line": 9
            },
            "start": {
                "character": 8,
                "line": 9
            }
        },
        "newText": "Printf(${1:})"
    },
    "detail": "func(format string, a ...interface{}) (n int, err error)"
}
```

**Comment by hujianxin** [comment]
@thomasfaingnaert Thanks very much, after setting ` 'usePlaceholders': v:true,`, that works.
