### ISSUE TITLE
Snippets do not aid in interface method implementation (Rust)

### ISSUE THREAD

**Issue by Bietola** [thomasfaingnaert/vim-lsp-ultisnips#12]
An example to elaborate the title:

In the following rust program (the cursor is marked with `$$`):
~~~ rust
struct Foo {
    name: String,
}

trait Bar {
    fn bar(&mut self, foo: Foo, s: String) -> Foo;
}

impl Bar for Foo {
    $$
}

fn main() {
    println!("Hello, world!");
}
~~~

If I write `fn ba` at the cursor position (again, where `$$` is), I get the following snippet completion:

~~~ rust
impl Bar for Foo {
    fn bar(foo: Foo, s: String)
}
~~~

which is incomplete... the complete one should be:

~~~ rust
impl Bar for Foo {
    fn bar(&mut self, foo: Foo, s: String) -> Foo
}
~~~

I guess it could just be that the snippet is expanded as if I was trying to *call* the `bar` function as a free function, and not as if I was implementing an interface method (which I am doing in this case). If this is what's happening here then I guess this isn't really an issue, but a feature request (that I would certainly enjoy very much!). Otherwise, how would I fix this?

**Comment by thomasfaingnaert** [comment]
This plugin only expands the snippets received by the language server, so you should open a feature request on the language server you are using.
Unless I'm misunderstanding something, and the language server does actually provide the correct snippet, but `vim-lsp-ultisnips` is picking up the wrong one?
