### ISSUE TITLE
UltiSnips Triggered doesn't work.

### ISSUE THREAD

**Issue by adam900710** [thomasfaingnaert/vim-lsp-ultisnips#7]
While the completion works fine, when hitting the keybind set in UltiSnipsExpandTrigger or UltiSnipJumpForwardTrigger, the triggers don't work

![2019-07-24-141433_1086x700_scrot](https://user-images.githubusercontent.com/460269/61769652-8e86e300-ae1d-11e9-8cc2-82a03432090e.png)

At that stage, hitting those trigger keys doesn't goes next parameter, but acts just like plain `Tab` key and `Ctrl-M` key

My vimrc looks like:
```
" UltiSnips
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-m>"
let g:UltiSnipsJumpBackwardTrigger="<c-m>"

autocmd Filetype c,h nnoremap <buffer> <silent> <c-]> :LspDefinition<cr>
autocmd FileType c,h set omnifunc=lsp#complete
autocmd FileType c,h set completefunc=lsp#complete
```

Any suggestion? The LSP server is clangd, the language is pure C.

**Comment by thomasfaingnaert** [comment]
Are you able to get to the point where the first trigger is selected, as in below screenshot?

![image](https://user-images.githubusercontent.com/10748726/61771441-279f0500-adf0-11e9-9102-2809b2753a23.png)

**Comment by adam900710** [comment]
Nope, that's exactly where I failed to do.

**Comment by thomasfaingnaert** [comment]
Just to make sure, are you hitting the accept completion key when a snippet in the completion menu is selected? (`C-y` by default)?

**Comment by adam900710** [comment]
Oh, hasn't accept that completion.

I'll double check the Ultisnip doc to tweak my config.

Thank you very much for the help!

**Comment by thomasfaingnaert** [comment]
@adam900710 
This is not because of UltiSnips, it's because I use `CompleteDone` autocmd, which is only fired if you explicitly accept the completion.

If you want to use another key to expand, something like this should work I believe:
```vim
inoremap <expr> some_key_here pumvisible() ? "\<C-y>" : some_key_here
```

**Comment by adam900710** [comment]
BTW, is it possible to generate some persistent parameter snippet?

E.g. after completing the following function:
```
btrfs_read_fs_root(struct btrfs_root *tree_root, struct btrfs_key *location)
```
If I didn't modify any parameter but go to other location, then came back the above completion,
currently I can't replace the completed parameter list any more, but delete them manually.

IIRC some other completion tool like vim-clang-completion can generate something like:
(I didn't remember the meta chars used there)
```
btrfs_read_fs_root($`struct btrfs_root *tree_root`, $`struct btrfs_key *location`)
```
And even I gave up the modification right now, next time I came back I can still continue completion.

**Comment by thomasfaingnaert** [comment]
I don't believe its possible with UltiSnips, because it tears down the snippet context when you leave insert mode. Might be worth it filing an issue at UltiSnips, though I'm not sure it's still actively maintained.

If you don't need UltiSnips, you can use custom functions that insert these special markers and then map your jump key to look for these characters.
