### ISSUE TITLE
Prevent text edit in buffer

### ISSUE THREAD

**Issue by ranebrown** [thomasfaingnaert/vim-lsp-ultisnips#8]
Is there a way to prevent the text in the buffer from being changed prior to accepting a completion? vim-lsp has the option [g:lsp_text_edit_enabled](https://github.com/prabirshrestha/vim-lsp/blob/cc6074a62436aa0c5c352277f91573066996a089/doc/vim-lsp.txt#L279) but the option has no affect when using this plugin.

**Comment by thomasfaingnaert** [comment]
Snippets are only expanded when the completion item is selected. Do you mean the text that Vim insert when scrolling through the completion menu? I believe you can change `'completeopt'` to disable that.

**Comment by ranebrown** [comment]
Yes, I was talking about the text that gets inserted when scrolling through the completion menu. I don't think it is related to vim's `completeopt` setting but to a feature of LSP. The same thing happens with vim-lsp but can be controlled with the setting I mentioned above.

Looks like some related information in prabirshrestha/vim-lsp#328

**Comment by thomasfaingnaert** [comment]
For me, Vim always insert the item in the completion menu, even without using this plugin and setting `g:lsp_text_edit_enabled` to `0`.

**Comment by thomasfaingnaert** [comment]
vim-lsp-ultisnips is now using the snippet integration from vim-lsp, so `g:lsp_text_edit_enabled` should be respected. If not, feel free to reopen an issue at https://github.com/prabirshrestha/vim-lsp.
